import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Cotton CLoud",
  description: "Generated by create next app",
  icons: {
    icon: "/cloud-fill.svg", // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className="m-0 p-0">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
          
          >
      <Header />
     

            {children}
          
          <Footer />
          

          <SanityLive />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
